[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_presale = "7eUBXQXEz6wh52VEmiucmcZL1eE6aFaANEY1URA9FRy4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/icus-ridwan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
